// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('sage-wall', ['ui.bootstrap']);

  app.controller('ProjectsController', [
    '$http', function($http) {
      var projectsCtrl;
      projectsCtrl = this;
      projectsCtrl.projects = [];
      return $http.get('data/projects.json').success(function(data) {
        return projectsCtrl.projects = data;
      });
    }
  ]);

  app.controller('ReportController', [
    '$http', function($http) {
      var reportCtrl;
      reportCtrl = this;
      reportCtrl.reports = [];
      return $http.get('data/reports.json').success(function(data) {
        return reportCtrl.reports = data;
      });
    }
  ]);

  app.controller('SkillController', [
    '$http', function($http) {
      var skillCtrl;
      skillCtrl = this;
      skillCtrl.skills = [];
      return $http.get('data/skills.json').success(function(data) {
        return skillCtrl.skills = data;
      });
    }
  ]);

  app.directive("projectDescription", function() {
    return {
      restrict: 'E',
      templateUrl: "project-description.html"
    };
  });

  app.directive("reportDescription", function() {
    return {
      restrict: 'E',
      templateUrl: "report-description.html"
    };
  });

}).call(this);

//# sourceMappingURL=app.js.map
